sonar.projectKey=benjaminduran_autoparts
sonar.organization=<tu_organizacion_sonarcloud>    # ej: benjaminduran
sonar.projectName=AutoParts-Duran-Tapia-Santis
sonar.language=py
sonar.sources=.
sonar.exclusions=**/migrations/**,**/.venv/**,**/static/**,**/media/**,**/templates/**,**/*.html
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
